//model

const appDiv = document.getElementById("app");
const model = {
  app: {
    pages: [
      "userLoginPage",
      "registerUserPage",
      "userProfilePage",
      "mainFeedPage",
      "chatInboxPage",
      "chatRoomPage",
      "adminPage",
      "feedProfilePage"
    ],
    currentPage: "userProfilePage",
  }, // app Syntax


  input: {
    loginUser: {
      id: null,
      username: null,
      password: null,
      logInMesssage: "",
    }, //loginInputs Syntax

    profile: {
      selectedUser: 0,
      selectedMatch: 4,
      selectedProfileUser: 3,
    },


    registerUser: {
      id: null,
      username: null,
      password: null,
      passwordConfirm: null,
      email: null,
      errorMessage: "",

      name: null,
      gender: null,
      location: null,
      age: null,

      showWomen: false,
      showMen: false,
      userOwner: null,
      bio: "",
      interests: [],
      liked: [],
      disliked: [],
      feed: [],
      mcClub: "",

      userIMG: "",
      userImages: [],

      isPrincessCat: false,
      agreedToEULA: true,
    }, //registerInputs Syntax
    profilePage: {
      inputBio: '',
    },
    messagesInput: {
      messageToPush: null,
      messages: [],
    }, //Messages Syntax
    mainFeed: {
      mainFeedMessage: '',
    },
    admin: {
    adminMessage: '',

  }, //Inputs Syntax
},
  data: {

    chatRooms:[],
    
    users: [
      {
        id: 0,
        username: "Roger",
        password: "123",
        email: "roger@gmail.com",
        isAdmin: true,
        owner: null,
        showMen: false,
        showWomen: true,
        name: "Roger",

        gender: "male",
        age: 34,
        location: "Larvik",
        bio: "Liker å skru, spille på slurva og kjøre sykkel",
        interests: [],
        interestsBox: ['Martial Arts', 'Riding Motorcycles','Surfing','The Office', 'Gaming','Netflix', 'Parkour', 'FurryBallin',],
        liked: [],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: false,

        feed: [],
        mcClub: "Hells Angels",
        userIMG: "Assets/Roger IMGS/1.png",
        userImages: ["Assets/Roger IMGS/1.png", "Assets/Roger IMGS/2.png", "Assets/Roger IMGS/3.png", "Assets/Roger IMGS/4.png"],
      },
      {
        //Male Users
        id: 1,
        username: "Andreas",
        password: "123",
        email: "andreas@getacademy.no",
        isAdmin: false,
        owner: null,
        showMen: false,
        showWomen: true,
        name: "Andreas",
        messages: [],

        gender: "male",
        age: 28,
        location: "Lakselv",
        bio: "Love to travel and explore new cultures.",
        interests: ["Teknologi", "Gaming", "Pumpe"],
        interestsBox: ['Martial Arts', 'Riding Motorcycles','Surfing','The Office', 'Gaming','Netflix', 'Parkour', 'FurryBallin',],
        liked: [],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: false,

        feed: [],
        mcClub: "Lakselv Bandidos",
        userIMG: "Assets/Boycats/boycat1.webp",
        userImages: ["Assets/Boycats/boycat4.webp","Assets/Boycats/boycat9.webp", "Assets/Boycats/boycat21.webp", "Assets/Boycats/boycat22.webp", "Assets/Boycats/boycat23.webp", "Assets/Boycats/boycat24.webp", "Assets/Boycats/boycat25.webp", "Assets/Boycats/boycat26.webp", "Assets/Boycats/boycat27.webp"],
      },

      {
        //Male Users
        id: 2,
        username: "Gerard",
        password: "123",
        email: "mrcat@hotmail.com",
        isAdmin: false,
        owner: null,
        showMen: true,
        showWomen: true,

        name: "Jimmy",

        gender: "male",
        age: 28,
        location: "Indre Østfold",
        bio: "Purr purr.",
        interests: ["FuttyBallin'", "Parkour",],
        interestsBox: ['Martial Arts', 'Riding Motorcycles','Surfing','The Office', 'Gaming','Netflix', 'Parkour', 'FurryBallin',],
        liked: [],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: true,

        feed: [],
        mcClub: "None",
        userIMG: "",
        userImages: ["Assets/Misc/catman.png","Assets/Misc/catperson.png"],
      },

      {
        id: 3,
        username: "norwegianNinja",
        password: "ninja123",
        email: "ninja@example.com",
        isAdmin: false,
        owner: null,
        showMen: false,
        showWomen: true,
        name: "Nils Nilsen",
        gender: "male",
        age: 25,
        location: "Oslo, Norway",
        bio: "Exploring the world, one martial art at a time.",
        interests: ["Martial Arts", "Gaming", "Netflix"],
        interestsBox: ["Martial Arts", "Riding Motorcycles", "Surfing", "The Office", "Gaming", "Netflix", "Parkour", "FurryBallin"],
        liked: [2, 3],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: false,
        feed: [],
        mcClub: "Ninja Clan",
        userIMG: "",
        userImages: ["Assets/Boycats/User/DALL·E 2024-11-11 12.49.02 - A highly realistic image of a brown cat dressed as a biker, standing upright with a leather jacket, motorcycle goggles, and a bandana. The cat has a c.webp", "Assets/Boycats/User/DALL·E 2024-11-11 12.49.03 - A highly realistic image of a brown cat dressed as a biker, standing upright with a leather jacket, motorcycle goggles, and a bandana. The cat has a c.webp","Assets/Boycats/User/DALL·E 2024-11-11 12.52.55 - A highly realistic image of a brown cat dressed as a biker, sitting on a motorcycle, with a leather jacket, aviator sunglasses, and a spiked collar. T.webp"],
      },
      {
        id: 4,
        username: "vikingRider",
        password: "viking123",
        email: "viking@example.com",
        isAdmin: false,
        owner: null,
        showMen: false,
        showWomen: true,
        name: "Olav Olsen",
        gender: "male",
        age: 29,
        location: "Bergen, Norway",
        bio: "Live to ride, ride to live. Adventure awaits!",
        interests: ["Riding Motorcycles", "Surfing"],
        interestsBox: ["Martial Arts", "Riding Motorcycles", "Surfing", "The Office", "Gaming", "Netflix", "Parkour", "FurryBallin"],
        liked: [1, 4],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: false,
        feed: [],
        mcClub: "Viking Riders",
        userIMG: "",
        userImages: ["Assets/Boycats/User/DALL·E 2024-11-11 12.51.10 - A highly realistic image of a brown cat dressed as a biker, posed in an action shot riding a motorcycle, wearing a leather jacket, aviator sunglasses,.webp", "Assets/Boycats/User/DALL·E 2024-11-11 12.51.11 - A highly realistic image of a brown cat dressed as a biker, posed in an action shot riding a motorcycle, wearing a leather jacket, aviator sunglasses,.webp"],
      },
      {
        id: 5,
        username: "fjordSurfer",
        password: "surfing123",
        email: "fjord.surfer@example.com",
        isAdmin: false,
        owner: null,
        showMen: false,
        showWomen: true,
        name: "Anders Andersen",
        gender: "male",
        age: 22,
        location: "Stavanger, Norway",
        bio: "Chasing waves and dreams in the fjords.",
        interests: ["Surfing", "Netflix", "The Office"],
        interestsBox: ["Martial Arts", "Riding Motorcycles", "Surfing", "The Office", "Gaming", "Netflix", "Parkour", "FurryBallin"],
        liked: [5, 6],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: false,
        feed: [],
        mcClub: "Fjord Surfers",
        userIMG: "",
        userImages: ["Assets/Boycats/User/DALL·E 2024-11-11 12.54.51 - A highly realistic image of a brown cat dressed as a biker, riding a motorcycle on an open road. The cat is wearing a leather jacket, aviator sunglass.webp", "Assets/Boycats/User/DALL·E 2024-11-11 12.54.52 - A highly realistic image of a brown cat dressed as a biker, riding a motorcycle on an open road. The cat is wearing a leather jacket, aviator sunglass.webp","Assets/Boycats/User/DALL·E 2024-11-11 12.54.54 - A highly realistic image of a brown cat dressed as a biker, riding confidently on a motorcycle down a desert highway. The cat is wearing a leather jac.webp",],
      },
      {
        id: 6,
        username: "parkourPanther",
        password: "panther456",
        email: "panther@example.com",
        isAdmin: false,
        owner: null,
        showMen: false,
        showWomen: true,
        name: "Petter Pedersen",
        gender: "male",
        age: 28,
        location: "Trondheim, Norway",
        bio: "Scaling walls and leaping boundaries.",
        interests: ["Parkour", "Martial Arts", "Gaming"],
        interestsBox: ["Martial Arts", "Riding Motorcycles", "Surfing", "The Office", "Gaming", "Netflix", "Parkour", "FurryBallin"],
        liked: [7, 8],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: false,
        feed: [],
        mcClub: "Panther Clan",
        userIMG: "",
        userImages: ["Assets/Boycats/User/DALL·E 2024-11-11 12.57.56 - A highly realistic photo of a grey cat dressed as a biker, wearing a leather jacket, aviator sunglasses, and a bandana. The cat has a bold, adventurou.webp", "Assets/Boycats/User/DALL·E 2024-11-11 12.57.57 - A highly realistic photo of a grey cat dressed as a biker, wearing a leather jacket, aviator sunglasses, and a bandana. The cat has a bold, adventurou.webp","Assets/Boycats/User/DALL·E 2024-11-11 12.57.59 - A highly realistic image of a grey biker cat in a peaceful moment outside a roadside diner, with the cat sitting on a bench next to a parked motorcycl.webp",],
      },
      {
        id: 7,
        username: "motorcycleMoose",
        password: "moose789",
        email: "moose@example.com",
        isAdmin: false,
        owner: null,
        showMen: false,
        showWomen: true,
        name: "Morten Mo",
        gender: "male",
        age: 31,
        location: "Oslo, Norway",
        bio: "Roaming the wilderness on two wheels.",
        interests: ["Riding Motorcycles", "Netflix"],
        interestsBox: ["Martial Arts", "Riding Motorcycles", "Surfing", "The Office", "Gaming", "Netflix", "Parkour", "FurryBallin"],
        liked: [3, 4],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: false,
        feed: [],
        mcClub: "Moose Riders",
        userIMG: "",
        userImages: ["Assets/Boycats/User/DALL·E 2024-11-11 12.58.08 - A highly realistic image of a different grey cat living the biker lifestyle, sitting confidently on a motorcycle at a desert highway stop. The cat is .webp", "Assets/Boycats/User/DALL·E 2024-11-11 12.58.10 - A highly realistic photo of a grey cat biker in a quiet moment, leaning against its motorcycle parked near a cliffside overlooking a vast landscape. T.webp"],
      },
      {
        id: 8,
        username: "theGamerBear",
        password: "bear123",
        email: "gamer.bear@example.com",
        isAdmin: false,
        owner: null,
        showMen: false,
        showWomen: true,
        name: "Bjørn Bjørnsen",
        gender: "male",
        age: 27,
        location: "Tromsø, Norway",
        bio: "Gaming through the polar nights.",
        interests: ["Gaming", "The Office", "Netflix"],
        interestsBox: ["Martial Arts", "Riding Motorcycles", "Surfing", "The Office", "Gaming", "Netflix", "Parkour", "FurryBallin"],
        liked: [1, 9],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: false,
        feed: [],
        mcClub: "Bear Gamers",
        userIMG: "",
        userImages: ["Assets/Boycats/User/DALL·E 2024-11-11 13.01.40 - A realistic image of an orange tabby cat biker, sitting on a motorcycle with a desert landscape in the background. The cat is wearing a worn leather j.webp", "Assets/Boycats/User/DALL·E 2024-11-11 13.01.37 - A highly realistic photo of an orange tabby cat living the biker lifestyle, leaning casually on a motorcycle at a roadside diner. The cat wears a leat.webp","Assets/Boycats/User/DALL·E 2024-11-11 13.01.36 - A highly realistic photo of an orange tabby cat living the biker lifestyle, leaning casually on a motorcycle at a roadside diner. The cat wears a leat.webp",],
      },
      {
        id: 9,
        username: "mountainGoat",
        password: "goat321",
        email: "mountain.goat@example.com",
        isAdmin: false,
        owner: null,
        showMen: false,
        showWomen: true,
        name: "Geir Geirsen",
        gender: "male",
        age: 24,
        location: "Bergen, Norway",
        bio: "Climbing mountains and exploring trails.",
        interests: ["Hiking", "Martial Arts"],
        interestsBox: ["Martial Arts", "Riding Motorcycles", "Surfing", "The Office", "Gaming", "Netflix", "Parkour", "FurryBallin"],
        liked: [2, 5],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: false,
        feed: [],
        mcClub: "Mountain Climbers",
        userIMG: "",
        userImages: ["Assets/Boycats/User/DALL·E 2024-11-11 13.03.42 - A highly realistic image of a black-and-white tuxedo cat biker, sitting proudly on a motorcycle at a scenic mountain overlook. The cat is dressed in a.webp", "Assets/Boycats/User/DALL·E 2024-11-11 13.03.43 - A highly realistic image of a black-and-white tuxedo cat biker, sitting proudly on a motorcycle at a scenic mountain overlook. The cat is dressed in a.webp", "Assets/Boycats/User/DALL·E 2024-11-11 13.03.45 - A realistic image of a black-and-white tuxedo cat biker, leaning against its motorcycle by a lake at sunset. The cat is wearing a leather jacket, gogg.webp",],
      },
      {
        id: 10,
        username: "theOfficeFan",
        password: "officefan123",
        email: "office.fan@example.com",
        isAdmin: false,
        owner: null,
        showMen: false,
        showWomen: true,
        name: "Ola Olsson",
        gender: "male",
        age: 32,
        location: "Oslo, Norway",
        bio: "Fan of The Office and all things comedy.",
        interests: ["The Office", "Gaming"],
        interestsBox: ["Martial Arts", "Riding Motorcycles", "Surfing", "The Office", "Gaming", "Netflix", "Parkour", "FurryBallin"],
        liked: [3, 10],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: false,
        feed: [],
        mcClub: "Comedy Club",
        userIMG: "",
        userImages: ["Assets/Boycats/User/DALL·E 2024-11-11 13.06.06 - A highly realistic photo of a calico cat living the biker lifestyle, captured in various everyday moments. In one scene, the cat, wearing a leather ja.webp", "Assets/Boycats/User/DALL·E 2024-11-11 13.06.07 - A highly realistic photo of a calico cat living the biker lifestyle, captured in various everyday moments. In one scene, the cat, wearing a leather ja.webp",],
      },
      {
        id: 11,
        username: "fjordFurry",
        password: "furry987",
        email: "fjord.furry@example.com",
        isAdmin: false,
        owner: null,
        showMen: false,
        showWomen: true,
        name: "Finn Fjord",
        gender: "male",
        age: 23,
        location: "Lofoten, Norway",
        bio: "Nature lover and proud FurryBallin' fan!",
        interests: ["FurryBallin'", "Martial Arts"],
        interestsBox: ["Martial Arts", "Riding Motorcycles", "Surfing", "The Office", "Gaming", "Netflix", "Parkour", "FurryBallin"],
        liked: [6],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: false,
        feed: [],
        mcClub: "Fjord Friends",
        userIMG: "",
        userImages: ["Assets/Boycats/User/DALL·E 2024-11-11 13.09.54 - A highly realistic series of images featuring a Siamese cat with a biker lifestyle. In one image, the cat sits on a motorcycle, wearing a leather jack.webp", "Assets/Boycats/User/DALL·E 2024-11-11 13.09.56 - A highly realistic series of images featuring a Siamese cat with a biker lifestyle. In one image, the cat sits on a motorcycle, wearing a leather jack.webp", "Assets/Boycats/User/DALL·E 2024-11-11 13.09.57 - A highly realistic photo of a Siamese biker cat, sitting calmly beside a motorcycle parked near a scenic overlook. The cat wears a leather jacket and .webp",],
      },
      {
        id: 12,
        username: "norwayNightRider",
        password: "night123",
        email: "night.rider@example.com",
        isAdmin: false,
        owner: null,
        showMen: false,
        showWomen: true,
        name: "Henrik Hansen",
        gender: "male",
        age: 34,
        location: "Kristiansand, Norway",
        bio: "Riding under the northern lights.",
        interests: ["Riding Motorcycles", "Gaming"],
        interestsBox: ["Martial Arts", "Riding Motorcycles", "Surfing", "The Office", "Gaming", "Netflix", "Parkour", "FurryBallin"],
        liked: [4, 8],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: false,
        feed: [],
        mcClub: "Night Riders",
        userIMG: "",
        userImages: ["Assets/Boycats/User/DALL·E 2024-11-11 13.12.40 - A realistic image of a Maine Coon cat biker, sitting proudly on a motorcycle with a leather jacket and bandana, parked at a scenic overlook by the mou.webp", "Assets/Boycats/User/DALL·E 2024-11-11 13.12.37 - A highly realistic series of images featuring a Maine Coon cat with a biker lifestyle. In one scene, the cat is wearing a leather vest and goggles, st.webp", "Assets/Boycats/User/DALL·E 2024-11-11 13.12.36 - A highly realistic series of images featuring a Maine Coon cat with a biker lifestyle. In one scene, the cat is wearing a leather vest and goggles, st.webp",],
      },


      //Female Users


      {
        id: 13,
        username: "Emma",
        password: "123",
        email: "emma.brown@example.com",
        isAdmin: false,
        owner: null,
        showMen: true,
        showWomen: false,
        name: "Emma",

        gender: "female",
        age: 25,
        location: "Oslo",
        bio: "Food lover and chef.",
        interests: ["Cooking", "Food"],
        interestsBox: ['Martial Arts', 'Riding Motorcycles','Surfing','The Office', 'Gaming','Netflix', 'Parkour', 'FurryBallin',],
        liked: [],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: false,

        feed: [],
        mcClub: "None",
        userIMG: "Assets/Girlcats/girlcat1.webp",
        userImages: ["Assets/Girlcats/girlcat1.webp"],
      },
      {
        id: 14,
        username: "Anna",
        password: "123",
        email: "anna.williams@example.com",
        isAdmin: false,
        owner: null,
        showMen: true,
        showWomen: false,
        name: "Anna",

        gender: "female",
        age: 30,
        location: "Bergen",
        bio: "Bookworm and writer.",
        interests: ["Reading", "Writing"],
        interestsBox: ['Martial Arts', 'Riding Motorcycles','Surfing','The Office', 'Gaming','Netflix', 'Parkour', 'FurryBallin',],
        liked: [],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: false,

        feed: [],
        mcClub: "None",
        userIMG: "",
        userImages: ["Assets/Girlcats/girlcat3.webp","Assets/Girlcats/girlcat2.webp"],
      },
      {
        id: 15,
        username: "Diana",
        password: "123",
        email: "diana.brown@example.com",
        isAdmin: false,
        owner: null,
        showMen: true,
        showWomen: false,
        name: "Diana",

        gender: "female",
        age: 25,
        location: "Buckingham Palace",
        bio: "I have a dog-servant.",
        interests: ["FurryBallin'", "Food"],
        interestsBox: ['Martial Arts', 'Riding Motorcycles','Surfing','The Office', 'Gaming','Netflix', 'Parkour', 'FurryBallin',],
        liked: [],
        disliked: [],
        messages: [],
        isPrincessCat: true,
        isImposter: false,

        feed: [],
        mcClub: "None",
        userIMG: "",
        userImages: ["Assets/Misc/pcatGrey.png", "Assets/Misc/pcatGrey2.png",],
      },
      {
        id: 16,
        username: "MissMargareth",
        password: "123",
        email: "margareth@example.com",
        isAdmin: false,
        owner: null,
        showMen: true,
        showWomen: false,
        name: "Emma",

        gender: "female",
        age: 25,
        location: "The Rockefeller Estate",
        bio: "Always hold your nose up high",
        interests: ["FurryBallin'", "Food"],
        interestsBox: ['Martial Arts', 'Riding Motorcycles','Surfing','The Office', 'Gaming','Netflix', 'Parkour', 'FurryBallin',],
        liked: [],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: false,

        feed: [],
        mcClub: "None",
        userIMG: "",
        userImages: ["Assets/Misc/pcatBrown.png","Assets/Misc/pcatGrey2.png",],
      },

      {
        id: 17,
        username: "norwegianExplorer",
        password: "explore123",
        email: "explorer@example.com",
        isAdmin: false,
        owner: null,
        showMen: true,
        showWomen: false,
        name: "Nora Nilsen",
        gender: "female",
        age: 28,
        location: "Oslo, Norway",
        bio: "Adventuring through the fjords and forests.",
        interests: ["Hiking", "Martial Arts", "Netflix"],
        interestsBox: ["Martial Arts", "Riding Motorcycles", "Surfing", "The Office", "Gaming", "Netflix", "Parkour", "FurryBallin"],
        liked: [2, 5],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: false,
        feed: [],
        mcClub: "Explorer Club",
        userIMG: "",
        userImages: ["Assets/Boycats/User/DALL·E 2024-11-11 13.14.10 - A realistic image of a female calico cat biker, dressed in a leather jacket with a pink bandana, leaning against her motorcycle at a sunset beach. The.webp", "Assets/Boycats/User/DALL·E 2024-11-11 13.14.09 - A highly realistic series of images featuring a female calico cat with a biker lifestyle. In one scene, the cat is dressed in a studded leather jacket.webp","Assets/Boycats/User/DALL·E 2024-11-11 13.14.08 - A highly realistic series of images featuring a female calico cat with a biker lifestyle. In one scene, the cat is dressed in a studded leather jacket.webp",],
      },
      {
        id: 18,
        username: "surfQueen",
        password: "surf456",
        email: "surfqueen@example.com",
        isAdmin: false,
        owner: null,
        showMen: true,
        showWomen: false,
        name: "Sara Sjølund",
        gender: "female",
        age: 26,
        location: "Bergen, Norway",
        bio: "Surfing the Norwegian waves, one beach at a time.",
        interests: ["Surfing", "The Office", "Gaming"],
        interestsBox: ["Martial Arts", "Riding Motorcycles", "Surfing", "The Office", "Gaming", "Netflix", "Parkour", "FurryBallin"],
        liked: [1, 3],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: false,
        feed: [],
        mcClub: "Wave Riders",
        userIMG: "",
        userImages: ["Assets/Boycats/User/DALL·E 2024-11-11 13.15.37 - A highly realistic series of images featuring a female tabby cat with a biker lifestyle. In one scene, the cat is wearing a leather jacket with a purp.webp", "Assets/Boycats/User/DALL·E 2024-11-11 13.15.38 - A highly realistic series of images featuring a female tabby cat with a biker lifestyle. In one scene, the cat is wearing a leather jacket with a purp.webp","Assets/Boycats/User/DALL·E 2024-11-11 13.15.39 - A realistic image of a female tabby cat biker, leaning on her motorcycle at the edge of a forest trail. She wears a leather jacket and a purple bandan.webp",],
      },
      {
        id: 19,
        username: "motorcycleMaven",
        password: "maven789",
        email: "motorcycle.maven@example.com",
        isAdmin: false,
        owner: null,
        showMen: true,
        showWomen: false,
        name: "Mari Madsen",
        gender: "female",
        age: 30,
        location: "Trondheim, Norway",
        bio: "Life on two wheels and endless roads.",
        interests: ["Riding Motorcycles", "Netflix"],
        interestsBox: ["Martial Arts", "Riding Motorcycles", "Surfing", "The Office", "Gaming", "Netflix", "Parkour", "FurryBallin"],
        liked: [4, 7],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: false,
        feed: [],
        mcClub: "Norway Bikers",
        userIMG: "",
        userImages: ["Assets/Boycats/User/DALL·E 2024-11-11 13.58.24 - A highly realistic series of three separate photos featuring a female ginger tabby cat with a biker lifestyle. In the first image, she stands beside h.webp", "Assets/Boycats/User/DALL·E 2024-11-11 13.58.25 - A highly realistic series of three separate photos featuring a female ginger tabby cat with a biker lifestyle. In the first image, she stands beside h.webp","",],
      },
      {
        id: 20,
        username: "fjordFox",
        password: "fox456",
        email: "fjord.fox@example.com",
        isAdmin: false,
        owner: null,
        showMen: true,
        showWomen: false,
        name: "Freya Fjord",
        gender: "female",
        age: 27,
        location: "Stavanger, Norway",
        bio: "Outdoor lover with a passion for photography.",
        interests: ["Photography", "Martial Arts", "Parkour"],
        interestsBox: ["Martial Arts", "Riding Motorcycles", "Surfing", "The Office", "Gaming", "Netflix", "Parkour", "FurryBallin"],
        liked: [2, 8],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: false,
        feed: [],
        mcClub: "Fjord Photography",
        userIMG: "",
        userImages: ["Assets/Girlcats/girlcat24.webp", "Assets/Girlcats/girlcat22.webp","Assets/Girlcats/girlcat25.webp",],
      },
      {
        id: 21,
        username: "nordicGamer",
        password: "game987",
        email: "nordic.gamer@example.com",
        isAdmin: false,
        owner: null,
        showMen: true,
        showWomen: false,
        name: "Ingrid Iversen",
        gender: "female",
        age: 24,
        location: "Oslo, Norway",
        bio: "Gaming through the long nights and snowy days.",
        interests: ["Gaming", "The Office", "Netflix"],
        interestsBox: ["Martial Arts", "Riding Motorcycles", "Surfing", "The Office", "Gaming", "Netflix", "Parkour", "FurryBallin"],
        liked: [1, 6],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: false,
        feed: [],
        mcClub: "Game Masters",
        userIMG: "",
        userImages: ["Assets/Boycats/User/DALL·E 2024-11-11 13.45.50 - A realistic image of a female Siamese cat biker, leaning on her motorcycle with a red bandana and leather jacket. She stands on a scenic overlook at s.webp","Assets/Boycats/User/DALL·E 2024-11-11 13.45.45 - A highly realistic series of images featuring a female Siamese cat with a love for motorcycles. In one image, the cat wears a leather jacket and a red.webp", "Assets/Boycats/User/DALL·E 2024-11-11 13.45.42 - A highly realistic series of images featuring a female Siamese cat with a love for motorcycles. In one image, the cat wears a leather jacket and a red.webp"],
      },
      {
        id: 22,
        username: "theArtistBear",
        password: "art321",
        email: "artist.bear@example.com",
        isAdmin: false,
        owner: null,
        showMen: true,
        showWomen: false,
        name: "Liv Larsen",
        gender: "female",
        age: 29,
        location: "Tromsø, Norway",
        bio: "Painting the world with colors and exploring nature.",
        interests: ["Art", "Hiking", "Gaming"],
        interestsBox: ["Martial Arts", "Riding Motorcycles", "Surfing", "The Office", "Gaming", "Netflix", "Parkour", "FurryBallin"],
        liked: [3, 10],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: false,
        feed: [],
        mcClub: "Art Club",
        userIMG: "",
        userImages: ["Assets/Boycats/User/DALL·E 2024-11-11 13.48.07 - A highly realistic series of images featuring a female calico cat with a biker lifestyle and motorcycle. In one image, the cat wears a leather jacket .webp", ""],
      },
      {
        id: 23,
        username: "theNordicHiker",
        password: "hike123",
        email: "nordic.hiker@example.com",
        isAdmin: false,
        owner: null,
        showMen: true,
        showWomen: false,
        name: "Sofie Solberg",
        gender: "female",
        age: 33,
        location: "Bergen, Norway",
        bio: "Taking every trail in the Norwegian mountains.",
        interests: ["Hiking", "Photography", "Martial Arts"],
        interestsBox: ["Martial Arts", "Riding Motorcycles", "Surfing", "The Office", "Gaming", "Netflix", "Parkour", "FurryBallin"],
        liked: [2, 9],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: false,
        feed: [],
        mcClub: "Hiking Legends",
        userIMG: "",
        userImages: ["Assets/Boycats/User/DALL·E 2024-11-11 13.52.37 - A series of three highly realistic, separate images featuring the same female calico cat with a biker lifestyle. In the first image, she stands beside.webp", "Assets/Boycats/User/DALL·E 2024-11-11 13.52.39 - A series of three highly realistic, separate images featuring the same female calico cat with a biker lifestyle. In the first image, she stands beside.webp","Assets/Boycats/User/DALL·E 2024-11-11 13.52.35 - A realistic image of the same female calico biker cat leaning on her motorcycle outside a diner at sunset, capturing a relaxed moment. She is wearing .webp",],
      },
      {
        id: 24,
        username: "queenOfWaves",
        password: "waves456",
        email: "queen.waves@example.com",
        isAdmin: false,
        owner: null,
        showMen: true,
        showWomen: false,
        name: "Helga Hansen",
        gender: "female",
        age: 21,
        location: "Kristiansand, Norway",
        bio: "Riding the waves and loving every splash.",
        interests: ["Surfing", "Netflix", "Parkour"],
        interestsBox: ["Martial Arts", "Riding Motorcycles", "Surfing", "The Office", "Gaming", "Netflix", "Parkour", "FurryBallin"],
        liked: [5, 10],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: false,
        feed: [],
        mcClub: "Wave Chasers",
        userIMG: "",
        userImages: ["Assets/Boycats/User/DALL·E 2024-11-11 13.53.41 - A new series of three realistic photos featuring the same female calico biker cat. In the first image, she sits confidently on her motorcycle, gazing .webp", "Assets/Boycats/User/DALL·E 2024-11-11 13.53.40 - A realistic photo of the same female calico biker cat, working on her motorcycle in a rustic garage. She’s wearing a leather jacket and purple bandana.webp","Assets/Boycats/User/DALL·E 2024-11-11 13.53.38 - A new series of three realistic photos featuring the same female calico biker cat. In the first image, she sits confidently on her motorcycle, gazing .webp",],
      },
      {
        id: 25,
        username: "norwegianFurry",
        password: "furryballin",
        email: "furry.norwegian@example.com",
        isAdmin: false,
        owner: null,
        showMen: true,
        showWomen: false,
        name: "Astrid Åsen",
        gender: "female",
        age: 22,
        location: "Lofoten, Norway",
        bio: "Proud FurryBallin' enthusiast and explorer.",
        interests: ["FurryBallin'", "Martial Arts"],
        interestsBox: ["Martial Arts", "Riding Motorcycles", "Surfing", "The Office", "Gaming", "Netflix", "Parkour", "FurryBallin"],
        liked: [6, 8],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: false,
        feed: [],
        mcClub: "Fjord Friends",
        userIMG: "",
        userImages: ["Assets/Boycats/User/DALL·E 2024-11-11 13.55.00 - A realistic photo of a female black cat biker, sitting confidently on her motorcycle with a leather jacket and red bandana. She looks out at an open r.webp", "Assets/Boycats/User/DALL·E 2024-11-11 13.54.58 - A series of three realistic photos featuring a female black cat with a biker lifestyle. In the first image, the cat stands beside her motorcycle in a .webp","Assets/Boycats/User/DALL·E 2024-11-11 13.54.58 - A series of three realistic photos featuring a female black cat with a biker lifestyle. In the first image, the cat stands beside her motorcycle in a  (1).webp",],
      },
      {
        id: 26,
        username: "theGamerQueen",
        password: "gamequeen",
        email: "gamer.queen@example.com",
        isAdmin: false,
        owner: null,
        showMen: true,
        showWomen: false,
        name: "Kari Karlsen",
        gender: "female",
        age: 30,
        location: "Oslo, Norway",
        bio: "Queen of strategy games and RPGs.",
        interests: ["Gaming", "Netflix", "The Office"],
        interestsBox: ["Martial Arts", "Riding Motorcycles", "Surfing", "The Office", "Gaming", "Netflix", "Parkour", "FurryBallin"],
        liked: [1, 7],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: false,
        feed: [],
        mcClub: "Game Queens",
        userIMG: "",
        userImages: ["Assets/Boycats/User/DALL·E 2024-11-11 13.57.10 - A realistic photo of the female black cat biker resting on her motorcycle by a desert road at sunset. She’s wearing a leather jacket and red bandana, .webp", "Assets/Boycats/User/DALL·E 2024-11-11 13.57.09 - A new series of three realistic photos featuring the same female black cat biker with her motorcycle. In the first image, she stands beside her bike i.webp","Assets/Boycats/User/DALL·E 2024-11-11 13.57.10 - A realistic photo of the female black cat biker resting on her motorcycle by a desert road at sunset. She’s wearing a leather jacket and red bandana, .webp",],
      },
      {
        id: 27,
        username: "Mcat",
        password: "123",
        email: "marie@getacademy.com",
        isAdmin: false,
        owner: null,
        showMen: true,
        showWomen: false,
        name: "Marie Askjem",
        gender: "female",
        age: 32,
        location: "Larvik, Norway",
        bio: "I absolutely love dogs.",
        interests: ["Dogs", "Ju-Jutsu", "Programming"],
        interestsBox: ["Martial Arts", "Riding Motorcycles", "Surfing", "The Office", "Gaming", "Netflix", "Parkour", "FurryBallin"],
        liked: [],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: false,
        feed: [],
        mcClub: "Paw Patrol",
        userIMG: "",
        userImages: ["Assets/Marie/marie1.jpeg","Assets/Marie/pexels-simonakidric-2607544.jpg","Assets/Marie/pexels-bri-schneiter-28802-346529.jpg"],
      },
      {
        id: 28,
        username: "peanut",
        password: "123",
        email: "jimmy@onparole.com",
        isAdmin: false,
        owner: null,
        showMen: true,
        showWomen: true,
        name: "Jimmy Nuts",
        gender: "male",
        age: 32,
        location: "Mysen, Norway",
        bio: "Mjaaaauu...",
        interests: ["Cat Litter", "Netflix",],
        interestsBox: ["Martial Arts", "Riding Motorcycles", "Surfing", "The Office", "Gaming", "Netflix", "Parkour", "FurryBallin"],
        liked: [],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: true,
        feed: [],
        mcClub: "None",
        userIMG: "",
        userImages: ["Assets/Misc/catperson.png","",""],
      },
      {
        id: 28,
        username: "Harley",
        password: "123",
        email: "harley@Catmail.com",
        isAdmin: true,
        owner: null,
        showMen: false,
        showWomen: true,
        name: "Harley Svendsen",
        gender: "male",
        age: 7,
        location: "Larvik",
        bio: "Booze, butterflyknives and greasy palms.",
        interests: ["Riding Motorcycles", "Netflix","Parkour"],
        interestsBox: ["Martial Arts", "Riding Motorcycles", "Surfing", "The Office", "Gaming", "Netflix", "Parkour", "FurryBallin"],
        liked: [],
        disliked: [],
        messages: [],
        isPrincessCat: false,
        isImposter: false,
        feed: [],
        mcClub: "Cats on Wheels",
        userIMG: "",
        userImages: ["Assets/harley.webp","Assets/DALL·E 2024-11-11 14.46.09 - A realistic black cat with vibrant green eyes, dressed as a biker with a leather jacket and red bandana, enjoying a lively party. The scene includes c.webp","Assets/DALL·E 2024-11-11 14.44.18 - A highly realistic photo of a black cat with vibrant green eyes, sitting confidently on a motorcycle in a scenic, sunlit mountain overlook. The cat lo.webp","Assets/DALL·E 2024-11-11 14.44.04 - A highly realistic photo of a black cat with vibrant green eyes, sitting confidently on a motorcycle in a scenic, sunlit mountain overlook. The cat lo.webp","",],
      },
      ], //Users Syntax
      
      adminPage: {
        bannedUser: [],
      
      },//adminPage Syntax
    }, //Data Syntax
}; //Model Syntax